name: Sreejath
favicon: null
layout_spectrum: 0.25271
typography_spectrum: 0
title: Camera Obscura
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#D8D0B0'
    - '#000000'
    - '#909880'
    - '#000000'
    - '#000000'
  brandStrength: 0.539784
  lightness: 0.524124
  saturation: 0.471017
  rhythmicContrast: 0.880822
purpose: []
