analytics: {}
color:
  brandColors:
    - '#D8D0B0'
    - '#000000'
    - '#909880'
    - '#000000'
    - '#000000'
  brandStrength: 0.539784
  lightness: 0.524124
  rhythmicContrast: 0.880822
  saturation: 0.471017
cta: {}
layout_spectrum: 0.996621
name: Sreejath
opengraph: {}
purpose: []
typography_spectrum: 0
