name: Sreejath
favicon: null
layout_spectrum: 0.25271
typography_spectrum: 0
title: Camera Obscura
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bbc2bb'
    - '#926544'
    - '#1d1c21'
    - '#427468'
    - '#e07488'
  brandStrength: 0.539784
  lightness: 0.524124
  saturation: 0.471017
  rhythmicContrast: 0.5
purpose: []
