name: Sreejath
favicon: null
layout_spectrum: 0.7654217784292996
typography_spectrum: 0.46748590655624866
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5397842957172543
  lightness: 0.5241245902143419
  saturation: 0.4710175539366901
  rhythmicContrast: 0.8808222196530551
purpose: []
